export type Article = { slug: string; category: string; title: string; description: string; intro: string; readTime: string; sections: { title: string; paragraphs: string[]; bullets?: string[] }[] };

export const articles: Article[] = [
  { slug: "kiedy-kwitnie-lawenda", category: "Kwitnienie", title: "Kiedy kwitnie lawenda w Polsce?", description: "Sprawdź, kiedy zaczyna się sezon lawendowy, od czego zależy termin kwitnienia i kiedy najlepiej odwiedzić pole lawendy.", intro: "Pełnia kwitnienia lawendy jest krótka i zależy od odmiany, stanowiska oraz przebiegu pogody. W Wielkopolsce najbardziej widowiskowy moment przypada zwykle na przełom czerwca i lipca.", readTime: "6 min", sections: [
    { title: "Kalendarz kwitnienia lawendy", paragraphs: ["Lawenda wąskolistna najczęściej rozpoczyna kwitnienie w drugiej połowie czerwca. W lipcu dołącza do niej lawandyna, która zwykle rośnie wyżej i kwitnie nieco później. Chłodna wiosna może opóźnić sezon, a ciepła i słoneczna — przyspieszyć go o kilka lub kilkanaście dni.", "Nie istnieje jedna data właściwa dla całej Polski. Dlatego przed wyjazdem na plantację najlepiej sprawdzić jej aktualne zdjęcia i komunikat gospodarzy."], bullets: ["druga połowa czerwca — początek kwitnienia wielu odmian", "przełom czerwca i lipca — najczęstsza pełnia koloru", "lipiec — stopniowe zbiory i kwitnienie późniejszych odmian"] },
    { title: "Kiedy przyjechać na zdjęcia?", paragraphs: ["Dla fotografów liczy się nie tylko liczba rozwiniętych kwiatów, lecz także światło. Najlepsze warunki zwykle pojawiają się rano albo w ostatnich dwóch godzinach przed zachodem słońca. W południe pole jest najjaśniejsze, ale kontrast i temperatura mogą utrudniać zdjęcia.", "Jeśli zależy Ci na szerokich, fioletowych kadrach, nie odkładaj wizyty do końca sezonu. Plantacja musi rozpocząć zbiory, kiedy kwiat ma odpowiednią jakość."] },
    { title: "Jak śledzić stan pola?", paragraphs: ["W sezonie będziemy publikować aktualny status kwitnienia na stronie oraz w mediach społecznościowych. To najbardziej wiarygodna wskazówka — zdjęcie wykonane kilka dni wcześniej mówi więcej niż sztywna data w kalendarzu."] }
  ]},
  { slug: "kiedy-przycinac-lawende", category: "Pielęgnacja", title: "Kiedy i jak przycinać lawendę?", description: "Praktyczny kalendarz cięcia lawendy: wiosna, lato i jesień. Zobacz, jak zachować zwarty kształt krzewu i nie uszkodzić starego drewna.", intro: "Regularne cięcie pomaga lawendzie zachować gęsty, półkulisty pokrój. Najważniejsza zasada jest prosta: tnij zielone przyrosty, ale ostrożnie obchodź się ze starym, bezlistnym drewnem.", readTime: "8 min", sections: [
    { title: "Wiosenne cięcie lawendy", paragraphs: ["Główne cięcie wykonuje się, gdy minie ryzyko silnych przymrozków i widać już młode przyrosty. Usuń pędy martwe, przemarznięte i połamane, a zdrowe skróć tak, aby odbudować zaokrąglony kształt krzewu.", "Nie ścinaj całej zielonej części i nie tnij głęboko w stare drewno. Lawenda regeneruje się z niego znacznie gorzej niż wiele popularnych krzewów."] },
    { title: "Cięcie po kwitnieniu", paragraphs: ["Latem usuwa się przekwitłe kwiatostany wraz z częścią zielonego przyrostu. Taki zabieg porządkuje krzew i może pobudzić go do słabszego, powtórnego kwitnienia. To także moment zbioru materiału na susz lub bukiety."], bullets: ["używaj czystych, ostrych nożyc", "formuj półkulę, żeby światło docierało równomiernie", "nie zostawiaj długich, łysiejących pędów"] },
    { title: "Czy ciąć lawendę jesienią?", paragraphs: ["Lekkie cięcie wczesną jesienią jest możliwe, ale nie warto wykonywać go zbyt późno. Młode przyrosty potrzebują czasu, aby przygotować się do zimy. W chłodniejszych rejonach bezpieczniej ograniczyć się do zebrania kwiatów i pozostawić mocniejsze formowanie na wiosnę."] },
    { title: "Najczęstszy błąd", paragraphs: ["Największym ryzykiem jest radykalne wejście w zdrewniałą, pozbawioną liści część krzewu. Jeśli stary egzemplarz jest mocno rozłożony i łysy w środku, odmładzaj go stopniowo zamiast ścinać jednorazowo niemal przy ziemi."] }
  ]},
  { slug: "jak-suszyc-lawende", category: "Zbiory", title: "Jak suszyć lawendę, żeby zachowała kolor i zapach?", description: "Dowiedz się, kiedy ścinać lawendę, jak wiązać bukiety i gdzie je suszyć, aby ograniczyć osypywanie kwiatów i utratę aromatu.", intro: "O jakości suszonej lawendy decydują trzy rzeczy: właściwy moment zbioru, przewiewne miejsce bez ostrego słońca oraz niezbyt duże pęczki. Pośpiech i wysoka wilgotność są tutaj największymi wrogami.", readTime: "7 min", sections: [
    { title: "Kiedy ścinać lawendę do suszenia?", paragraphs: ["Na bukiety przeznaczone do suszenia najlepiej wybierać pędy, na których część kwiatów jest już rozwinięta, ale cały kłos nie zdążył przekwitnąć. Zbieraj w suchy dzień, po ustąpieniu rosy. Mokry materiał schnie wolniej i łatwiej traci jakość.", "Jeśli celem jest pozyskanie aromatycznego suszu, moment zbioru może różnić się od terminu ścinania lawendy dekoracyjnej. Warto osobno oceniać wygląd i intensywność zapachu."] },
    { title: "Suszenie krok po kroku", paragraphs: ["Usuń uszkodzone lub zabrudzone fragmenty, wyrównaj łodygi i zwiąż je w niewielkie pęczki. Zawieś kwiatostanami w dół w suchym, zacienionym i przewiewnym miejscu."], bullets: ["nie płucz kwiatów przed suszeniem", "nie twórz bardzo grubych bukietów", "unikaj bezpośredniego słońca", "zapewnij cyrkulację powietrza", "chroń susz przed wilgocią"] },
    { title: "Jak przechowywać susz?", paragraphs: ["Dobrze wysuszone kwiaty oddziel od łodyg dopiero wtedy, gdy są kruche i łatwo się osypują. Przechowuj je w szczelnym opakowaniu, w ciemnym i suchym miejscu. Woreczki zapachowe mogą być przewiewne, ale zapas suszu lepiej chronić przed powietrzem i światłem."] },
    { title: "Dlaczego lawenda traci kolor?", paragraphs: ["Najczęstszą przyczyną jest suszenie w pełnym słońcu. Promieniowanie przyspiesza blaknięcie, a wysoka temperatura może osłabiać aromat. Brązowienie i nieprzyjemny zapach częściej wskazują natomiast na zbyt dużą wilgotność lub zbyt ciasno związany bukiet."] }
  ]},
  { slug: "jak-sadzic-lawende", category: "Uprawa", title: "Jak sadzić lawendę w ogrodzie? Termin, rozstawa i przygotowanie miejsca", description: "Praktyczny poradnik sadzenia lawendy: wybór stanowiska, przygotowanie ziemi, rozstawa sadzonek i pielęgnacja po posadzeniu.", intro: "Dobre sadzenie zaczyna się jeszcze przed wykopaniem dołka. Lawenda potrzebuje przede wszystkim słońca, przepuszczalnej ziemi i miejsca, w którym po deszczu nie stoi woda. Jeśli te trzy warunki są spełnione, dalsza pielęgnacja staje się znacznie prostsza.", readTime: "9 min", sections: [
    { title: "Kiedy sadzić lawendę?", paragraphs: ["Sadzonki z pojemników można sadzić od wiosny do wczesnej jesieni, o ile ziemia nie jest zamarznięta ani przesuszona. Najbezpieczniejsza jest wiosna, gdy minie ryzyko silnych przymrozków. Roślina ma wtedy cały sezon na rozbudowanie korzeni przed pierwszą zimą.", "Sadzenie latem wymaga większej uwagi przy podlewaniu. Jesienią nie warto czekać do ostatniej chwili: lawenda powinna zdążyć się ukorzenić, zanim nadejdą długie chłody."] },
    { title: "Stanowisko i przygotowanie ziemi", paragraphs: ["Wybierz miejsce słoneczne i przewiewne. Lawenda słabo kwitnie w głębokim cieniu, a w stale mokrej ziemi jej korzenie są narażone na gnicie. Na ciężkiej glebie rozważ podniesioną rabatę albo popraw przepuszczalność podłoża materiałem mineralnym.", "Przed sadzeniem usuń chwasty wieloletnie i sprawdź, jak szybko po obfitym podlaniu odpływa woda. Nie zasypuj dołka samym torfem ani bardzo żyznym kompostem — lawenda nie potrzebuje podłoża zatrzymującego dużo wilgoci."] },
    { title: "Jaka rozstawa sadzonek?", paragraphs: ["Rozstawę dobiera się do docelowej wielkości odmiany i efektu, jaki chcesz osiągnąć. Małe odmiany na obwódki można sadzić gęściej, a silnie rosnącą lawendę i lawandynę trzeba rozsunąć szerzej. Zbyt ciasne sadzenie ogranicza przepływ powietrza i utrudnia późniejsze cięcie."], bullets: ["na niską obwódkę zwykle potrzeba mniejszych odstępów", "w luźnej rabacie zostaw miejsce na półkulisty pokrój", "sprawdź docelową szerokość konkretnej odmiany na etykiecie", "nie planuj rozstawy wyłącznie według rozmiaru młodej sadzonki"] },
    { title: "Sadzenie krok po kroku", paragraphs: ["Namocz bryłę korzeniową, wykop dołek nieco szerszy od doniczki i ustaw roślinę na tej samej głębokości, na której rosła wcześniej. Zasyp przestrzeń przygotowaną ziemią, lekko dociśnij i podlej. Szyjka korzeniowa nie powinna znaleźć się w zagłębieniu zbierającym wodę.", "Przez pierwsze tygodnie kontroluj wilgotność, ale nie utrzymuj stale mokrego podłoża. Gdy sadzonka się przyjmie, podlewaj rzadziej i głębiej. Kolejnym krokiem jest regularne formowanie młodego krzewu — opisujemy je w poradniku o cięciu lawendy."] }
  ]},
  { slug: "jaka-ziemia-do-lawendy", category: "Uprawa", title: "Jaka ziemia do lawendy? Podłoże, drenaż i odczyn gleby", description: "Zobacz, jakiej ziemi potrzebuje lawenda w gruncie i donicy, jak poprawić drenaż oraz po czym poznać zbyt ciężkie podłoże.", intro: "Lawenda lepiej wybacza skromne nawożenie niż zalegającą wodę. Dlatego przy przygotowaniu stanowiska najpierw myśl o odpływie wilgoci, strukturze ziemi i nasłonecznieniu, a dopiero później o dokarmianiu.", readTime: "8 min", sections: [
    { title: "Najważniejsza jest przepuszczalność", paragraphs: ["Korzenie lawendy potrzebują dostępu do powietrza. Dobra ziemia po podlaniu przyjmuje wodę, ale jej nadmiar sprawnie odpływa. Ciężka glina, zaskorupiające się podłoże i zagłębienia terenu zwiększają ryzyko problemów szczególnie jesienią i zimą.", "Jeśli po deszczu kałuże utrzymują się długo, samo wsypanie garści piasku do dołka nie rozwiąże problemu. Skuteczniejsza bywa szersza poprawa struktury rabaty, podniesienie stanowiska albo uprawa w dużym pojemniku."] },
    { title: "Jaki odczyn lubi lawenda?", paragraphs: ["Lawenda preferuje podłoże od obojętnego do lekko zasadowego i źle znosi silnie kwaśną ziemię. Zamiast wapnować na oko, warto zbadać pH — prosty pomiar pomaga dobrać zabieg do rzeczywistego stanu gleby.", "Odczyn zmieniaj stopniowo i zgodnie z zaleceniami dla użytego preparatu. Zbyt duża dawka wapna również może ograniczać dostępność części składników pokarmowych."] },
    { title: "Czego dodać do ciężkiej ziemi?", paragraphs: ["Celem nie jest stworzenie kieszeni całkiem innego podłoża, lecz poprawa odpływu wody w strefie korzeni. Pomagają materiały mineralne o odpowiedniej frakcji, żwir, grys albo drobne kruszywo wymieszane z większą objętością ziemi. Na podmokłym terenie najpewniejsza jest podniesiona rabata."], bullets: ["nie sadź lawendy w miejscu, do którego spływa woda", "unikaj bardzo dużej ilości świeżej materii organicznej", "nie używaj samego drobnego piasku do rozluźniania gliny", "po poprawie ziemi ponownie sprawdź jej odpływ"] },
    { title: "Ziemia do lawendy w donicy", paragraphs: ["W pojemniku wybierz lekkie podłoże i donicę z dużymi otworami odpływowymi. Osłonka bez odpływu może zatrzymywać wodę nawet wtedy, gdy sama mieszanka jest dobra. Po podlaniu zawsze usuń nadmiar wody z podstawki.", "Podłoże z czasem osiada i traci strukturę. Wiosną sprawdź, czy woda nadal swobodnie przepływa oraz czy korzenie nie wypełniły całej donicy. Jeśli tak, przesadź roślinę do nieco większego pojemnika."] }
  ]},
  { slug: "jak-podlewac-lawende", category: "Pielęgnacja", title: "Jak podlewać lawendę? W gruncie, po posadzeniu i w doniczce", description: "Dowiedz się, jak często podlewać lawendę, czym różni się podlewanie młodych i starszych roślin oraz jak rozpoznać przelanie.", intro: "Najczęstszy błąd w podlewaniu lawendy nie polega na jednodniowym przesuszeniu, lecz na utrzymywaniu stale mokrych korzeni. Potrzeby rośliny zmieniają się jednak wraz z jej wiekiem, pogodą i miejscem uprawy.", readTime: "8 min", sections: [
    { title: "Podlewanie po posadzeniu", paragraphs: ["Świeżo posadzona lawenda ma jeszcze niewielki system korzeniowy, dlatego przez pierwsze tygodnie trzeba kontrolować wilgotność częściej. Podlewaj obficie, a potem poczekaj, aż wierzchnia warstwa ziemi zacznie przesychać. Małe porcje wody podawane codziennie sprzyjają płytkiemu ukorzenianiu.", "W upałach sprawdzaj roślinę rano. Nie oceniaj wilgotności wyłącznie po kolorze powierzchni — ziemia kilka centymetrów niżej może być nadal mokra."] },
    { title: "Starsza lawenda w gruncie", paragraphs: ["Dobrze ukorzeniona lawenda zwykle radzi sobie z krótkimi okresami suszy. Podlewania potrzebuje głównie podczas długotrwałego braku opadów, szczególnie na bardzo lekkiej glebie. Lepiej podlać rzadziej, ale tak, aby woda dotarła głębiej.", "Kieruj strumień na ziemię, nie na środek krzewu. Moczenie liści i zdrewniałej podstawy przy chłodnej pogodzie niepotrzebnie zwiększa wilgotność wewnątrz rośliny."] },
    { title: "Lawenda w doniczce", paragraphs: ["Pojemnik wysycha szybciej niż grunt, więc w lecie wymaga regularnej kontroli. Podlewaj dopiero po przeschnięciu górnej warstwy podłoża i pozwól, aby nadmiar wody wypłynął otworami. Nie pozostawiaj donicy na stałe w pełnej podstawce."], bullets: ["mała doniczka przesycha szybciej niż duża", "ciemny pojemnik mocniej nagrzewa korzenie", "wiatr zwiększa tempo wysychania", "osłonka bez odpływu wymaga szczególnej ostrożności"] },
    { title: "Objawy przelania i przesuszenia", paragraphs: ["Więdnięcie nie zawsze oznacza brak wody. Przy przelaniu podstawa pędów może ciemnieć, ziemia długo pozostaje wilgotna, a roślina mimo to traci jędrność. Najpierw sprawdź podłoże i drożność odpływu, dopiero później sięgaj po konewkę.", "Przesuszona roślina w donicy ma lekką bryłę korzeniową i suche podłoże odchodzące od ścianek. Nawadniaj ją spokojnie, kilkoma porcjami, aby woda nie przepłynęła natychmiast bokiem."] }
  ]},
  { slug: "lawenda-w-donicy", category: "Uprawa", title: "Lawenda w donicy — sadzenie, pielęgnacja i zimowanie", description: "Kompletny poradnik uprawy lawendy w doniczce na balkonie i tarasie: pojemnik, podłoże, podlewanie, cięcie oraz zima.", intro: "Lawenda może dobrze rosnąć na balkonie i tarasie, ale w donicy szybciej reaguje na zalanie, suszę i mróz. Powodzenie zależy głównie od dużego odpływu, słonecznego miejsca oraz rozsądnego podlewania.", readTime: "10 min", sections: [
    { title: "Jaka donica będzie dobra?", paragraphs: ["Wybierz stabilny pojemnik z kilkoma dużymi otworami odpływowymi. Powinien być wyraźnie większy od bryły korzeniowej, ale nie musi od razu osiągać ogromnych rozmiarów. Ważniejsze od ozdobnej osłonki jest to, czy po deszczu woda może szybko wypłynąć.", "Donice ceramiczne oddają wilgoć szybciej, natomiast lekkie pojemniki z tworzywa wolniej przesychają. Niezależnie od materiału nie ustawiaj ich w miejscu stale zalewanym przez wodę z dachu."] },
    { title: "Sadzenie i stanowisko", paragraphs: ["Użyj przepuszczalnego podłoża przeznaczonego dla roślin lubiących suchsze warunki i rozluźnij je materiałem mineralnym. Posadź lawendę na tej samej głębokości, na której rosła w szkółce. Po pierwszym podlaniu sprawdź, czy woda swobodnie wypływa.", "Ustaw donicę w miejscu otrzymującym kilka godzin bezpośredniego słońca. W cieniu pędy wydłużają się, krzew traci zwarty kształt i słabiej kwitnie."] },
    { title: "Pielęgnacja przez sezon", paragraphs: ["Kontroluj podłoże palcem, zamiast podlewać według sztywnego kalendarza. Po kwitnieniu usuń kwiatostany i lekko uformuj zielone przyrosty. Nie dopuszczaj, aby lawenda przez wiele lat rosła bez cięcia, ponieważ środek krzewu szybciej się ogołoci."], bullets: ["regularnie opróżniaj podstawkę", "obracaj donicę, jeśli światło dociera tylko z jednej strony", "nie przesadzaj z nawozem azotowym", "obserwuj, czy otwory odpływowe nie są zatkane"] },
    { title: "Jak przezimować lawendę w donicy?", paragraphs: ["Korzenie w pojemniku są bardziej narażone na mróz niż te rosnące w gruncie. Przed zimą ustaw donicę w zacisznym miejscu, odizoluj ją od zimnego podłoża i zabezpiecz boki materiałem przepuszczającym powietrze. Nie zamykaj rośliny szczelnie w folii.", "Zimą lawenda nadal nie może stać w wodzie. Podczas długich okresów bez mrozu sprawdź, czy bryła korzeniowa nie wyschła całkowicie, ale podlewaj bardzo oszczędnie."] }
  ]},
  { slug: "lawenda-zima", category: "Pielęgnacja", title: "Lawenda zimą — jak przygotować ją do mrozu i wilgoci?", description: "Sprawdź, jak przygotować lawendę do zimy w gruncie i donicy, kiedy ograniczyć cięcie oraz dlaczego nadmiar wilgoci bywa groźniejszy od mrozu.", intro: "Zimą lawendzie szkodzi nie tylko niska temperatura. Równie ważne są odmiana, wiatr, zastoiska wody i gwałtowne zmiany pogody. Przygotowanie roślin zaczyna się więc już przy wyborze stanowiska.", readTime: "9 min", sections: [
    { title: "Która lawenda najlepiej zimuje?", paragraphs: ["W polskich ogrodach najpewniejszym wyborem jest zwykle lawenda wąskolistna. Odporność różni się jednak między odmianami, a roślina osłabiona przez mokrą ziemię lub późne nawożenie może gorzej przetrwać zimę. Lawenda francuska jest znacznie bardziej wrażliwa i najczęściej wymaga zimowania poza mrozem.", "Kupując sadzonkę, sprawdź pełną nazwę gatunku i odmiany. Ogólna etykieta „lawenda” nie mówi wystarczająco dużo o mrozoodporności."] },
    { title: "Co zrobić jesienią?", paragraphs: ["Nie pobudzaj lawendy do miękkiego wzrostu późnym nawożeniem azotowym. Usuń chwasty wokół rośliny i zadbaj, aby woda nie gromadziła się przy podstawie. Mocne cięcie zostaw na wiosnę, szczególnie jeśli jesień jest chłodna i wilgotna.", "Zdrowe pędy zatrzymują nieco śniegu, który działa jak naturalna izolacja. Nie ścinaj krzewu nisko przed samym nadejściem mrozów."] },
    { title: "Czy lawendę trzeba okrywać?", paragraphs: ["Młode rośliny i bardziej narażone stanowiska można zabezpieczyć przewiewnym materiałem, na przykład stroiszem. Osłona powinna ograniczać działanie mroźnego wiatru, ale nie może tworzyć mokrego, szczelnego kokonu."], bullets: ["okrywaj po nadejściu trwałych chłodów, nie podczas ciepłej jesieni", "unikaj szczelnej folii", "zabezpiecz przede wszystkim młode sadzonki", "wiosną zdejmuj osłonę stopniowo"] },
    { title: "Lawenda po zimie", paragraphs: ["Nie oceniaj krzewu zbyt wcześnie. Szare liście i suche końcówki nie zawsze oznaczają, że cała roślina obumarła. Poczekaj na wyraźne ruszenie wegetacji, a następnie usuń martwe pędy i uformuj zdrową część.", "Jeśli lawenda wypada regularnie po każdej zimie, przyczyną może być stanowisko, nie sam mróz. Sprawdź odpływ wody, ilość słońca i gatunek rośliny przed ponownym sadzeniem."] }
  ]},
  { slug: "olejek-lawendowy-a-hydrolat", category: "Produkty", title: "Olejek lawendowy a hydrolat — czym się różnią i jak je przechowywać?", description: "Poznaj różnice między olejkiem lawendowym i hydrolatem: sposób powstawania, intensywność zapachu, przechowywanie oraz bezpieczne podejście do użycia.", intro: "Olejek lawendowy i hydrolat powstają podczas destylacji, ale nie są tym samym produktem. Różnią się składem, koncentracją, zapachem i sposobem użycia. Ta różnica ma znaczenie szczególnie wtedy, gdy kupujesz je po raz pierwszy.", readTime: "7 min", sections: [
    { title: "Co powstaje podczas destylacji?", paragraphs: ["Podczas destylacji para wodna przechodzi przez materiał roślinny i przenosi jego lotne składniki. Po schłodzeniu otrzymuje się fazę wodną, czyli hydrolat, oraz niewielką ilość oddzielającego się olejku eterycznego.", "Olejek jest silnie skoncentrowany i ma intensywny aromat. Hydrolat zawiera głównie wodę oraz niewielką część związków aromatycznych, dlatego pachnie łagodniej i ma inną trwałość."] },
    { title: "Najważniejsze różnice", paragraphs: ["Olejek i hydrolat nie powinny być traktowane zamiennie. Olejek eteryczny zwykle stosuje się w bardzo małych ilościach i zgodnie z przeznaczeniem podanym przez producenta. Hydrolat jest produktem wodnym, bardziej podatnym na zmiany zapachu i jakości po otwarciu."], bullets: ["olejek: skoncentrowany, intensywny, używany w małych ilościach", "hydrolat: wodny, delikatniejszy, zwykle mniej trwały po otwarciu", "oba produkty: wymagają czystego opakowania i ochrony przed światłem", "zawsze sprawdzaj etykietę oraz deklarowane przeznaczenie konkretnego produktu"] },
    { title: "Jak przechowywać?", paragraphs: ["Trzymaj produkty szczelnie zamknięte, z dala od słońca i źródeł ciepła. Nie przelewaj ich do przypadkowych, nieopisanych butelek. Hydrolat po otwarciu warto szczególnie chronić przed zanieczyszczeniem i obserwować jego zapach, kolor oraz zalecany termin zużycia.", "Data minimalnej trwałości i warunki przechowywania zależą od sposobu produkcji oraz opakowania. Najbardziej wiarygodne są informacje podane przez wytwórcę na etykiecie."] },
    { title: "Bezpieczne użycie", paragraphs: ["Naturalne pochodzenie nie oznacza, że każdy produkt można stosować w dowolny sposób. Olejku eterycznego nie nakładaj nierozcieńczonego na skórę i nie spożywaj, jeśli producent wyraźnie nie przewidział takiego zastosowania. Zachowaj ostrożność przy dzieciach, zwierzętach, ciąży, alergiach i chorobach przewlekłych.", "Ten poradnik wyjaśnia różnice między produktami, ale nie zastępuje informacji z etykiety ani porady medycznej. Gdy masz wątpliwości dotyczące użycia, zapytaj lekarza, farmaceutę lub osobę posiadającą odpowiednie kwalifikacje."] }
  ]}
];

export function getArticle(slug: string) { return articles.find((article) => article.slug === slug); }

export function getRelatedArticles(article: Article, limit = 3) {
  const candidates = articles.filter((candidate) => candidate.slug !== article.slug);
  return [...candidates.filter((candidate) => candidate.category === article.category), ...candidates.filter((candidate) => candidate.category !== article.category)].slice(0, limit);
}
